### ISSUE TITLE
making detail page

### ISSUE THREAD

**Issue by ahmadbasir** [ahmadbasir/ahmadbasir.github.io#1]
make detail page, with your own stylesheet

noted:
- do not use template bootstrap or other front-end template

**Comment by VisheshSingh** [comment]
@ahmadbasir There is very little information to understand what you are expecting, Could you be more specific?

**Comment by ahmadbasir** [comment]
@VisheshSingh oh i am sorry, i mean is like to create a page that contains details of a post
